[package]
name = "l89"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { version = "1" }
lazy_static = { version = "1" }
chainchomp = { version = "0.2.1" }

[dev-dependencies]
pretty_assertions = { version = "1" }
